### ISSUE TITLE
source code?

### ISSUE THREAD

**Issue by yifuguo** [grugq/portal#1]
I'm quiet confused as to why this project's source isn't provided.

**Comment by grugq** [comment]
Source code and build instructions are here: http://wiki.openwrt.org/doc/howto/buildroot.exigence

**Comment by yifuguo** [comment]
as far as I'm concerned this project includes custom deploy stack script of some sort that is built on top of the standard openWRT image, that's the source code I'm referring to, not openWRT.

**Comment by grugq** [comment]
It doesn't include any such script. It is OpenWRT w/ tor-alpha (and a bunch of packages to support various USB devices), and then configuration files to make everything work.

**Comment by yifuguo** [comment]
So is there a source (list) for the packages and the configuration file?

Much appreciated.
